[package]
name = "inject_derive"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
getset = "0.1.2"
proc-macro2 = "1.0.51"
quote = "1.0.23"
syn = "1.0.109"